INSERT INTO countries (code,"name") VALUES
	 ('AF','Afghanistan'),
	 ('AX','Åland Islands'),
	 ('AL','Albania'),
	 ('DZ','Algeria'),
	 ('AS','American Samoa'),
	 ('AD','Andorra'),
	 ('AO','Angola'),
	 ('AI','Anguilla'),
	 ('AQ','Antarctica'),
	 ('AG','Antigua and Barbuda');
INSERT INTO countries (code,"name") VALUES
	 ('AR','Argentina'),
	 ('AM','Armenia'),
	 ('AW','Aruba'),
	 ('AU','Australia'),
	 ('AT','Austria'),
	 ('AZ','Azerbaijan'),
	 ('BS','Bahamas'),
	 ('BH','Bahrain'),
	 ('BD','Bangladesh'),
	 ('BB','Barbados');
INSERT INTO countries (code,"name") VALUES
	 ('BY','Belarus'),
	 ('BE','Belgium'),
	 ('BZ','Belize'),
	 ('BJ','Benin'),
	 ('BM','Bermuda'),
	 ('BT','Bhutan'),
	 ('BO','Bolivia, Plurinational State of'),
	 ('BQ','Bonaire, Sint Eustatius and Saba'),
	 ('BA','Bosnia and Herzegovina'),
	 ('BW','Botswana');
INSERT INTO countries (code,"name") VALUES
	 ('BV','Bouvet Island'),
	 ('BR','Brazil'),
	 ('IO','British Indian Ocean Territory'),
	 ('BN','Brunei Darussalam'),
	 ('BG','Bulgaria'),
	 ('BF','Burkina Faso'),
	 ('BI','Burundi'),
	 ('CV','Cabo Verde'),
	 ('KH','Cambodia'),
	 ('CM','Cameroon');
INSERT INTO countries (code,"name") VALUES
	 ('CA','Canada'),
	 ('KY','Cayman Islands'),
	 ('CF','Central African Republic'),
	 ('TD','Chad'),
	 ('CL','Chile'),
	 ('CN','China'),
	 ('CX','Christmas Island'),
	 ('CC','Cocos (Keeling) Islands'),
	 ('CO','Colombia'),
	 ('KM','Comoros');
INSERT INTO countries (code,"name") VALUES
	 ('CG','Congo'),
	 ('CD','Congo, Democratic Republic of the'),
	 ('CK','Cook Islands'),
	 ('CR','Costa Rica'),
	 ('CI','Côte d''Ivoire'),
	 ('HR','Croatia'),
	 ('CU','Cuba'),
	 ('CW','Curaçao'),
	 ('CY','Cyprus'),
	 ('CZ','Czechia');
INSERT INTO countries (code,"name") VALUES
	 ('DK','Denmark'),
	 ('DJ','Djibouti'),
	 ('DM','Dominica'),
	 ('DO','Dominican Republic'),
	 ('EC','Ecuador'),
	 ('EG','Egypt'),
	 ('SV','El Salvador'),
	 ('GQ','Equatorial Guinea'),
	 ('ER','Eritrea'),
	 ('EE','Estonia');
INSERT INTO countries (code,"name") VALUES
	 ('SZ','Eswatini'),
	 ('ET','Ethiopia'),
	 ('FK','Falkland Islands (Malvinas)'),
	 ('FO','Faroe Islands'),
	 ('FJ','Fiji'),
	 ('FI','Finland'),
	 ('FR','France'),
	 ('GF','French Guiana'),
	 ('PF','French Polynesia'),
	 ('TF','French Southern Territories');
INSERT INTO countries (code,"name") VALUES
	 ('GA','Gabon'),
	 ('GM','Gambia'),
	 ('GE','Georgia'),
	 ('DE','Germany'),
	 ('GH','Ghana'),
	 ('GI','Gibraltar'),
	 ('GR','Greece'),
	 ('GL','Greenland'),
	 ('GD','Grenada'),
	 ('GP','Guadeloupe');
INSERT INTO countries (code,"name") VALUES
	 ('GU','Guam'),
	 ('GT','Guatemala'),
	 ('GG','Guernsey'),
	 ('GN','Guinea'),
	 ('GW','Guinea-Bissau'),
	 ('GY','Guyana'),
	 ('HT','Haiti'),
	 ('HM','Heard Island and McDonald Islands'),
	 ('VA','Holy See'),
	 ('HN','Honduras');
INSERT INTO countries (code,"name") VALUES
	 ('HK','Hong Kong'),
	 ('HU','Hungary'),
	 ('IS','Iceland'),
	 ('IN','India'),
	 ('ID','Indonesia'),
	 ('IR','Iran, Islamic Republic of'),
	 ('IQ','Iraq'),
	 ('IE','Ireland'),
	 ('IM','Isle of Man'),
	 ('IL','Israel');
INSERT INTO countries (code,"name") VALUES
	 ('IT','Italy'),
	 ('JM','Jamaica'),
	 ('JP','Japan'),
	 ('JE','Jersey'),
	 ('JO','Jordan'),
	 ('KZ','Kazakhstan'),
	 ('KE','Kenya'),
	 ('KI','Kiribati'),
	 ('KP','Korea, Democratic People''s Republic of'),
	 ('KR','Korea, Republic of');
INSERT INTO countries (code,"name") VALUES
	 ('KW','Kuwait'),
	 ('KG','Kyrgyzstan'),
	 ('LA','Lao People''s Democratic Republic'),
	 ('LV','Latvia'),
	 ('LB','Lebanon'),
	 ('LS','Lesotho'),
	 ('LR','Liberia'),
	 ('LY','Libya'),
	 ('LI','Liechtenstein'),
	 ('LT','Lithuania');
INSERT INTO countries (code,"name") VALUES
	 ('LU','Luxembourg'),
	 ('MO','Macao'),
	 ('MG','Madagascar'),
	 ('MW','Malawi'),
	 ('MY','Malaysia'),
	 ('MV','Maldives'),
	 ('ML','Mali'),
	 ('MT','Malta'),
	 ('MH','Marshall Islands'),
	 ('MQ','Martinique');
INSERT INTO countries (code,"name") VALUES
	 ('MR','Mauritania'),
	 ('MU','Mauritius'),
	 ('YT','Mayotte'),
	 ('MX','Mexico'),
	 ('FM','Micronesia, Federated States of'),
	 ('MD','Moldova, Republic of'),
	 ('MC','Monaco'),
	 ('MN','Mongolia'),
	 ('ME','Montenegro'),
	 ('MS','Montserrat');
INSERT INTO countries (code,"name") VALUES
	 ('MA','Morocco'),
	 ('MZ','Mozambique'),
	 ('MM','Myanmar'),
	 ('NA','Namibia'),
	 ('NR','Nauru'),
	 ('NP','Nepal'),
	 ('NL','Netherlands, Kingdom of the'),
	 ('NC','New Caledonia'),
	 ('NZ','New Zealand'),
	 ('NI','Nicaragua');
INSERT INTO countries (code,"name") VALUES
	 ('NE','Niger'),
	 ('NG','Nigeria'),
	 ('NU','Niue'),
	 ('NF','Norfolk Island'),
	 ('MK','North Macedonia'),
	 ('MP','Northern Mariana Islands'),
	 ('NO','Norway'),
	 ('OM','Oman'),
	 ('PK','Pakistan'),
	 ('PW','Palau');
INSERT INTO countries (code,"name") VALUES
	 ('PS','Palestine, State of'),
	 ('PA','Panama'),
	 ('PG','Papua New Guinea'),
	 ('PY','Paraguay'),
	 ('PE','Peru'),
	 ('PH','Philippines'),
	 ('PN','Pitcairn'),
	 ('PL','Poland'),
	 ('PT','Portugal'),
	 ('PR','Puerto Rico');
INSERT INTO countries (code,"name") VALUES
	 ('QA','Qatar'),
	 ('RE','Réunion'),
	 ('RO','Romania'),
	 ('RU','Russian Federation'),
	 ('RW','Rwanda'),
	 ('BL','Saint Barthélemy'),
	 ('SH','Saint Helena, Ascension and Tristan da Cunha'),
	 ('KN','Saint Kitts and Nevis'),
	 ('LC','Saint Lucia'),
	 ('MF','Saint Martin (French part)');
INSERT INTO countries (code,"name") VALUES
	 ('PM','Saint Pierre and Miquelon'),
	 ('VC','Saint Vincent and the Grenadines'),
	 ('WS','Samoa'),
	 ('SM','San Marino'),
	 ('ST','Sao Tome and Principe'),
	 ('SA','Saudi Arabia'),
	 ('SN','Senegal'),
	 ('RS','Serbia'),
	 ('SC','Seychelles'),
	 ('SL','Sierra Leone');
INSERT INTO countries (code,"name") VALUES
	 ('SG','Singapore'),
	 ('SX','Sint Maarten (Dutch part)'),
	 ('SK','Slovakia'),
	 ('SI','Slovenia'),
	 ('SB','Solomon Islands'),
	 ('SO','Somalia'),
	 ('ZA','South Africa'),
	 ('GS','South Georgia and the South Sandwich Islands'),
	 ('SS','South Sudan'),
	 ('ES','Spain');
INSERT INTO countries (code,"name") VALUES
	 ('LK','Sri Lanka'),
	 ('SD','Sudan'),
	 ('SR','Suriname'),
	 ('SJ','Svalbard and Jan Mayen'),
	 ('SE','Sweden'),
	 ('CH','Switzerland'),
	 ('SY','Syrian Arab Republic'),
	 ('TW','Taiwan, Province of China'),
	 ('TJ','Tajikistan'),
	 ('TZ','Tanzania, United Republic of');
INSERT INTO countries (code,"name") VALUES
	 ('TH','Thailand'),
	 ('TL','Timor-Leste'),
	 ('TG','Togo'),
	 ('TK','Tokelau'),
	 ('TO','Tonga'),
	 ('TT','Trinidad and Tobago'),
	 ('TN','Tunisia'),
	 ('TR','Türkiye'),
	 ('TM','Turkmenistan'),
	 ('TC','Turks and Caicos Islands');
INSERT INTO countries (code,"name") VALUES
	 ('TV','Tuvalu'),
	 ('UG','Uganda'),
	 ('UA','Ukraine'),
	 ('AE','United Arab Emirates'),
	 ('US','United States of America'),
	 ('UM','United States Minor Outlying Islands'),
	 ('UY','Uruguay'),
	 ('UZ','Uzbekistan'),
	 ('VU','Vanuatu'),
	 ('VE','Venezuela, Bolivarian Republic of');
INSERT INTO countries (code,"name") VALUES
	 ('VN','Viet Nam'),
	 ('VG','Virgin Islands (British)'),
	 ('VI','Virgin Islands (U.S.)'),
	 ('WF','Wallis and Futuna'),
	 ('EH','Western Sahara'),
	 ('YE','Yemen'),
	 ('ZM','Zambia'),
	 ('ZW','Zimbabwe'),
	 ('GB','United Kingdom of Great Britain and Northern Ireland');
